// Generated by CoffeeScript 1.7.1
(function() {
  var app;

  app = angular.module('myApp', []);

  app.controller('RoomCtrl', function() {
    this.openDoor = function() {
      return alert(this.doorSound);
    };
    this.doorSound = 'creeeeaaaak';
    this.doorName = 'My Door';
    debugger;
    return this;
  });

}).call(this);
